// ──────────────────────────────────────────────
// Factory functions for DRY constant generation
// ──────────────────────────────────────────────

function createEntityErrors(entity: string, entityLower: string, entityPluralLower?: string) {
	const plural = entityPluralLower || `${entityLower}s`;
	return {
		VALIDATION_FAILED: `${entity} validation failed`,
		INVALID_ID_FORMAT: `Invalid ${entityLower} ID format`,
		NOT_FOUND: `${entity} not found`,
		CREATE_FAILED: `Error creating ${entityLower}`,
		UPDATE_FAILED: `Error updating ${entityLower}`,
		DELETE_FAILED: `Error deleting ${entityLower}`,
		GET_FAILED: `Error getting ${entityLower}`,
		GET_ALL_FAILED: `Error getting ${plural}`,
		ERROR_GETTING: `Error getting ${entityLower}`,
		ERROR_UPDATING: `Error updating ${entityLower}`,
		ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
	};
}

function createEntitySuccess(entity: string, entityPlural: string, entityLower: string) {
	return {
		CREATED: `${entity} created successfully`,
		UPDATED: `${entity} updated successfully`,
		DELETED: `${entity} deleted successfully`,
		RETRIEVED: `${entity} retrieved successfully`,
		RETRIEVED_ALL: `${entityPlural} retrieved successfully`,
		GETTING_BY_ID: `Getting ${entityLower} by ID`,
	};
}

function createActivityLog(entityUpper: string, entity: string, entityLower: string) {
	return {
		ACTIONS: {
			CREATE: `CREATE_${entityUpper}`,
			GET_ALL: `GET_ALL_${entityUpper}`,
			GET: `GET_${entityUpper}`,
			UPDATE: `UPDATE_${entityUpper}`,
			DELETE: `DELETE_${entityUpper}`,
		},
		DESCRIPTIONS: {
			CREATED: `Created new ${entityLower}`,
			UPDATED: `Updated ${entityLower}`,
			DELETED: `Deleted ${entityLower}`,
			RETRIEVED: `Retrieved ${entityLower} details`,
			LIST_RETRIEVED: `Retrieved ${entityLower} list`,
		},
		PAGES: {
			CREATION: `${entity} Creation`,
			UPDATE: `${entity} Update`,
			DELETION: `${entity} Deletion`,
			DETAILS: `${entity} Details`,
			LIST: `${entity} List`,
		},
	};
}

function createAuditLogEntity(entityLower: string) {
	return {
		DESCRIPTIONS: {
			CREATED: `Created new ${entityLower}`,
			UPDATED: `Updated ${entityLower}`,
			DELETED: `Deleted ${entityLower}`,
		},
	};
}

// ──────────────────────────────────────────────
// Config
// ──────────────────────────────────────────────

export const config = {
	DEFAULT_UNKNOWN_USER_ID: "unknown",
	ERROR: {
		PERSON: {
			...createEntityErrors("Person", "person", "persons"),
			INVALID_ID: "Invalid person ID",
			MISSING_ID: "Missing person ID",
			USER_ID_REQUIRED: "Person ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting person",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			ERROR_UPDATING_USER: "Error updating person",
			ERROR_DELETING_USER: "Error deleting person",
			GETTING_ALL_USERS: "Getting all persons",
		},
		USER: {
			...createEntityErrors("User", "user", "users"),
			INVALID_ID: "Invalid user ID",
			MISSING_ID: "Missing user ID",
			USER_ID_REQUIRED: "User ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting user",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			ERROR_UPDATING_USER: "Error updating user",
			ERROR_DELETING_USER: "Error deleting user",
			INVALID_USER_ID_FORMAT: "Invalid user ID format",
			INVALID_FIELDS_PARAMETER: "Invalid fields parameter",
			INVALID_QUERY_PARAMETERS: "Invalid query parameters",
			INVALID_UPDATE_DATA: "Invalid update data",
			REQUEST_BODY_EMPTY: "Request body cannot be empty",
			FIRST_NAME_REQUIRED: "First name is required",
			LAST_NAME_REQUIRED: "Last name is required",
			UNAUTHORIZED_USER_ID_NOT_FOUND: "Unauthorized - User ID not found",
			ERROR_DURING_USER_CREATION: "Error during user creation",
			FAILED_TO_CREATE_OR_FIND_PERSON: "Failed to create or find person",
			UPLOADING_AVATAR: "Uploading avatar for user",
			AVATAR_UPLOADED: "Avatar uploaded successfully",
			ORGANIZATION_VERIFIED: "Organization verified",
			USER_ALREADY_EXISTS: "User already exists",
			INVALID_ID_FORMAT: "Invalid user ID format",
		},
		AUTH: {
			UNAUTHORIZED: "Unauthorized",
			INVALID_TOKEN: "Invalid token",
			REGISTRATION_VALIDATION_FAILED: "Registration validation failed",
			LOGIN_VALIDATION_FAILED: "Login validation failed",
			PASSWORD_UPDATE_VALIDATION_FAILED: "Password update validation failed",
			FIRST_NAME_LAST_NAME_REQUIRED: "First name and last name are required",
			INVALID_ORGANIZATION_ID_FORMAT: "Invalid organization ID format",
			ORGANIZATION_NOT_FOUND: "Organization not found",
			USER_ALREADY_EXISTS: "User already exists",
			ERROR_DURING_REGISTRATION: "Error during registration",
			INVALID_CREDENTIALS: "Invalid credentials",
			ERROR_DURING_LOGIN: "Error during login",
			USER_ID_PASSWORD_REQUIRED: "User ID and new password are required",
			PASSWORD_MIN_LENGTH: "Password must be at least 6 characters long",
			ERROR_UPDATING_PASSWORD: "Error updating password",
			USER_NOT_FOUND: "User not found",
			FAILED_TO_CREATE_OR_FIND_PERSON: "Failed to create or find person",
		},
		TEMPLATE: createEntityErrors("Template", "template", "templates"),
		ROLE: createEntityErrors("Role", "role", "roles"),
		ORGANIZATION: createEntityErrors("Organization", "organization", "organizations"),
		ACTIVITYLOG: createEntityErrors("ActivityLog", "activitylog", "activitylogs"),
		AUDITLOG: createEntityErrors("AuditLog", "auditlog", "auditlogs"),
		NOTIFICATION: createEntityErrors("Notification", "notification", "notifications"),
		SYSTEMLOG: createEntityErrors("SystemLog", "systemlog", "systemlogs"),
		METRICS: createEntityErrors("Metrics", "metrics", "metrics"),
		COURSE: createEntityErrors("Course", "course", "courses"),
		FACULTY: createEntityErrors("Faculty", "faculty", "faculties"),
		PROGRAM: createEntityErrors("Program", "program", "programs"),
		QUERY_PARAMS: {
			INVALID_ID: "Invalid ID",
			MISSING_ID: "ID parameter is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate must be a string",
			INVALID_PAGE: "Invalid page",
			INVALID_LIMIT: "Invalid limit",
			INVALID_ORDER: "Invalid order",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
			INVALID_SORT: "Invalid sort",
			SORT_MUST_BE_STRING: "Sort must be a string",
			INVALID_FILTER: "Invalid filter",
			FILTER_MUST_BE_STRING: "Filter must be a string",
			INVALID_QUERY: "Invalid query",
			QUERY_MUST_BE_STRING: "Query must be a string",
			INVALID_DOCUMENT: "Invalid document",
			DOCUMENT_MUST_BE_STRING: "Document must be a string",
			INVALID_PAGINATION: "Invalid pagination",
			PAGINATION_MUST_BE_STRING: "Pagination must be a string",
			INVALID_COUNT: "Invalid count",
			COUNT_MUST_BE_STRING: "Count must be a string",
			INVALID_GROUPBY: "Invalid groupBy",
			INVALID_COMBINATION: "Invalid combination",
		},
		COMMON: {
			SUPPLIER_ID: "Require Supplier Id or Source Id",
			INTERNAL_SERVER_ERROR: "Internal server error",
			VALIDATION_ERROR: "Validation error",
			NOT_FOUND: "Resource not found",
			UNAUTHORIZED: "Unauthorized access",
			NO_UPDATE_FIELDS: "No fields provided for update",
		},
	},
	INFO: {
		USER: {
			REGISTERING_USER: "Registering user with email:",
			CREATING_USER_WITH_PERSON_ID: "Creating user with personId:",
			LOGGING_IN_USER: "Logging in user with email:",
		},
	},
	SUCCESS: {
		AUTH: {
			REGISTRATION_SUCCESSFUL: "Registration successful",
			LOGGED_IN_SUCCESSFULLY: "Logged in successfully",
			PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
			USER_CREATED: "User created successfully",
			TOKEN_GENERATED: "Token generated successfully",
			ORGANIZATION_VERIFIED: "Organization verified successfully",
			USER_LOGGED_IN: "User logged in successfully",
		},
		COMMON: {
			OPERATION_SUCCESSFUL: "Operation completed successfully",
		},
		PERSON: {
			...createEntitySuccess("Person", "Persons", "person"),
			SOFT_DELETING: "Soft deleting user",
			GETTING_USER_BY_ID: "Getting person by ID",
			GETTING_ALL_USERS: "Getting all persons",
		},
		USER: {
			...createEntitySuccess("User", "Users", "user"),
		},
		TEMPLATE: createEntitySuccess("Template", "Templates", "template"),
		ROLE: createEntitySuccess("Role", "Roles", "role"),
		ORGANIZATION: createEntitySuccess("Organization", "Organizations", "organization"),
		ACTIVITYLOG: createEntitySuccess("ActivityLog", "ActivityLogs", "activitylog"),
		AUDITLOG: createEntitySuccess("AuditLog", "AuditLogs", "auditlog"),
		NOTIFICATION: createEntitySuccess("Notification", "Notifications", "notification"),
		SYSTEMLOG: createEntitySuccess("SystemLog", "SystemLogs", "systemlog"),
		METRICS: createEntitySuccess("Metrics", "Metrics", "metrics"),
		COURSE: createEntitySuccess("Course", "Courses", "course"),
		FACULTY: createEntitySuccess("Faculty", "Faculties", "faculty"),
		PROGRAM: createEntitySuccess("Program", "Programs", "program"),
	},

	ACTIVITY_LOG: {
		ORGANIZATION: createActivityLog("ORGANIZATION", "Organization", "organization"),
		METRICS: createActivityLog("METRICS", "Metrics", "metrics"),
		SYSTEMLOG: createActivityLog("SYSTEMLOG", "SystemLog", "systemlog"),
		NOTIFICATION: createActivityLog("NOTIFICATION", "Notification", "notification"),
		AUDITLOG: createActivityLog("AUDITLOG", "AuditLog", "auditlog"),
		ACTIVITYLOG: createActivityLog("ACTIVITYLOG", "ActivityLog", "activitylog"),
		ROLE: createActivityLog("ROLE", "Role", "role"),
		PERSON: createActivityLog("PERSON", "Person", "person"),
		COURSE: createActivityLog("COURSE", "Course", "course"),
		FACULTY: createActivityLog("FACULTY", "Faculty", "faculty"),
		PROGRAM: createActivityLog("PROGRAM", "Program", "program"),
		USER: {
			...createActivityLog("USER", "User", "user"),
			ACTIONS: {
				...createActivityLog("USER", "User", "user").ACTIONS,
				REGISTER: "USER_REGISTRATION",
			},
			DESCRIPTIONS: {
				...createActivityLog("USER", "User", "user").DESCRIPTIONS,
				USER_REGISTERED: "User registered",
			},
			PAGES: {
				...createActivityLog("USER", "User", "user").PAGES,
			},
		},
		TEMPLATE: {
			...createActivityLog("TEMPLATE", "Template", "template"),
			ACTIONS: {
				...createActivityLog("TEMPLATE", "Template", "template").ACTIONS,
				USER_LOGIN: "USER_LOGIN",
				USER_LOGOUT: "USER_LOGOUT",
				USER_REGISTRATION: "USER_REGISTRATION",
				PASSWORD_UPDATE: "PASSWORD_UPDATE",
			},
			DESCRIPTIONS: {
				...createActivityLog("TEMPLATE", "Template", "template").DESCRIPTIONS,
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
				USER_REGISTERED: "User registered",
				PASSWORD_CHANGED: "Password changed",
			},
			PAGES: {
				...createActivityLog("TEMPLATE", "Template", "template").PAGES,
				USER_LOGIN: "User Login",
				USER_REGISTRATION: "User Registration",
				PASSWORD_CHANGE: "Password Change",
			},
		},
	},

	AUDIT_LOG: {
		ACTIONS: {
			CREATE: "CREATE",
			READ: "READ",
			UPDATE: "UPDATE",
			DELETE: "DELETE",
			LOGIN: "LOGIN",
			LOGOUT: "LOGOUT",
			REGISTER: "REGISTER",
		},
		RESOURCES: {
			TEMPLATE: "templates",
			USERS: "users",
			ORGANIZATIONS: "organizations",
			AUTH: "auth",
			PERSON: "person",
			ROLE: "role",
			USER: "user",
			BATCH: "batch",
			STOCK: "stock",
			SUPPLIER: "supplier",
			PURCHASEORDERITEM: "purchaseorderitem",
			LOCATION: "location",
			STOCKRECORD: "stockrecord",
			ORGANIZATION: "organization",
			ITEM: "item",
			SUPPLIERITEM: "supplieritem",
			ALERT: "alert",
			ACTIVITYLOG: "activitylog",
			AUDITLOG: "auditlog",
			NOTIFICATION: "notification",
			SYSTEMLOG: "systemlog",
			STOCKMOVEMENTITEM: "stockmovementitem",
			PRICE: "price",
			METRICS: "metrics",
			PATIENT: "patient",
			MEDICINE: "medicine",
			APPROVAL: "approval",
			COURSE: "courses",
			FACULTY: "faculties",
			PROGRAM: "programs",
		},
		SEVERITY: {
			LOW: "LOW" as const,
			MEDIUM: "MEDIUM" as const,
			HIGH: "HIGH" as const,
			CRITICAL: "CRITICAL" as const,
		},
		ENTITY_TYPES: {
			TEMPLATE: "template",
			USER: "user",
			ORGANIZATION: "organization",
			PERSON: "person",
			ROLE: "role",
			BATCH: "batch",
			STOCK: "stock",
			SUPPLIER: "supplier",
			PURCHASEORDERITEM: "purchaseorderitem",
			LOCATION: "location",
			STOCKRECORD: "StockRecord",
			ITEM: "item",
			SUPPLIERITEM: "supplieritem",
			ALERT: "alert",
			ACTIVITYLOG: "activitylog",
			AUDITLOG: "auditlog",
			NOTIFICATION: "notification",
			SYSTEMLOG: "systemlog",
			STOCKMOVEMENTITEM: "stockmovementitem",
			PRICE: "price",
			METRICS: "metrics",
			PATIENT: "patient",
			MEDICINE: "medicine",
			APPROVAL: "approval",
			COURSE: "course",
			FACULTY: "faculty",
			PROGRAM: "program",
		},
		PERSON: createAuditLogEntity("person"),
		ROLE: createAuditLogEntity("role"),
		USER: createAuditLogEntity("user"),
		BATCH: createAuditLogEntity("batch"),
		STOCK: createAuditLogEntity("stock"),
		SUPPLIER: createAuditLogEntity("supplier"),
		PURCHASEORDERITEM: createAuditLogEntity("purchaseorderitem"),
		LOCATION: createAuditLogEntity("location"),
		STOCKRECORD: {
			DESCRIPTIONS: {
				CREATED: "Stock record created",
				UPDATED: "Stock record updated",
				DELETED: "Stock record deleted",
			},
		},
		ORGANIZATION: createAuditLogEntity("organization"),
		ITEM: createAuditLogEntity("item"),
		SUPPLIERITEM: createAuditLogEntity("supplieritem"),
		ALERT: createAuditLogEntity("alert"),
		ACTIVITYLOG: createAuditLogEntity("activitylog"),
		AUDITLOG: createAuditLogEntity("auditlog"),
		NOTIFICATION: createAuditLogEntity("notification"),
		SYSTEMLOG: createAuditLogEntity("systemlog"),
		STOCKMOVEMENTITEM: createAuditLogEntity("stockmovementitem"),
		PRICE: createAuditLogEntity("price"),
		METRICS: createAuditLogEntity("metrics"),
		PATIENT: createAuditLogEntity("patient"),
		MEDICINE: createAuditLogEntity("medicine"),
		APPROVAL: createAuditLogEntity("approval"),
		COURSE: createAuditLogEntity("course"),
		FACULTY: createAuditLogEntity("faculty"),
		PROGRAM: createAuditLogEntity("program"),
		TEMPLATE: {
			DESCRIPTIONS: {
				...createAuditLogEntity("template").DESCRIPTIONS,
				USER_CREATED: "Created new user",
				USER_UPDATED: "Updated user",
				USER_DELETED: "Deleted user",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
			},
		},
	},
	AUTH_CONFIG: {
		standard: "1d",
		persistent: undefined,
		temporary: "1h",
	} as const,
};

export type roles = "user" | "admin" | "viewer";
